AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
   TweetSentimentMetrics:
     Type: AWS::Serverless::Function
     Properties:
        CodeUri: target/TweetSentiment-1.0.0.jar
        Runtime: java8
        Handler: com.amazonaws.serverless.tweetsentiment.lambda.TweetSentimentHandler::handleRequest
        Tracing: Active
        MemorySize: 512
        Timeout: 60
        #Policies:
        Environment:
          Variables:
            MY_VAR: 42
